#!/bin/bash

num_rounds=10

# Run no thread, no cache thrash.
#for i in $(seq 1 "$num_rounds"); do
#	perf stat -e cache-misses -a ./mem-walk-no-thread-no-thrash
#done
#
## Run no thread, thrash the cache.
#for i in $(seq 1 "$num_rounds"); do
#	perf stat -e cache-misses -a ./mem-walk-no-thread
#done
#
## Run one thread per CPU, no cache thrash.
#for i in $(seq 1 "$num_rounds"); do
#	perf stat -e cache-misses -a ./mem-walk-no-thrash
#done

# Run one thread per CPU, thrash the cache.
for i in $(seq 1 "$num_rounds"); do
	perf stat -e cache-misses -a ./mem-walk
done
